--- #YAML:1.0
name:               File-Shuffle
version:            0.10
abstract:           Randomly shuffles lines in a file.
author:
    - Jeff Kubina (jeff.kubina@gmail.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dump:      1.19
    Sort::External:  0.18
    Test::More:      0.96
    Test::Simple:    0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
